spring:
  application:
    name: learning
  mongodb:
    uri: ${MONGO_URI}

logging:
  level:
    root: INFO
    com.michael.learning: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG